config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  #root to: 'homes#index'
  root 'homes#index'
  resources :users
  resources :rooms do
    resources :videos
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :videos, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #====以下、関連付けの記述====================================================
  # has_many => このmodelに紐づく "子のmodel" （Railsの命名規則から複数形で指定する）
  # 詳細はER図参照（daisuke_portfolio1.puml）
  #========================================================================
  has_many :rooms
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :room
  URL_STRING_REGEX = /v=(.{11})/

  def fetch_from_url
    if self.youtube_url.present?
      youtube_url.match(URL_STRING_REGEX)[1]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @room = Room.new
  end

  def index
    @rooms = Room.all
  end

  def create
    #　フォームから送られてくるストロングパラメータ
    @room = Room.new(room_params)
    ###binding.pry
    #　deviceのhelpermethod "current_user(サインインしているユーザーを取得)"
    #　"current_user.id"　でユーザーIDを追加代入（フォームからは渡されていないパラメータの為）
    @room.user_id = current_user.id
    ###binding.pry
    if @room.save
      redirect_to rooms_path, notice: "新規の部屋が作成されました。"
    else
      flash.now[:alert] = "新規の部屋の作成に失敗しました。"
      @rooms = Room.all
      render :index
    end
  end

  def show
    @room = Room.find(params[:id])
    # 以下、modelの関連付けにより "子に紐づく親要素" を呼び出している
    # "room" に紐づく親要素は "user" (一意)のみのため、単数形 "user" で呼び出す
    # model "user.rb","room.rb" を参照
    @user = @room.user
    @video = Video.new
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      redirect_to rooms_path
      flash[:success] = "部屋を編集しました。"
    else
      flash.now[:alert] = "部屋の編集に失敗しました。"
      render :edit
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  #ストロングパラメータのカラム
  private
  def room_params
    params.require(:room).permit(:room_name,:room_text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # 以下、modelの関連付けにより "親に紐づく子要素" を呼び出している
    # "user" に紐づく子要素は "rooms"（多義）のため、複数形 "rooms" で呼び出す
    # model "user.rb","room.rb" を参照
    @rooms = @user.rooms
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def create
    @room = Room.find(params[:room_id])
    @video = @room.videos.build(video_params)
    @video.youtube_url = @video.fetch_from_url
    if @video.save
      flash[:notice] = '新規の動画が投稿されました。'
      redirect_to controller: 'rooms', action: 'show', id: @room.id
    else
      flash.now[:alert] = '動画の投稿に失敗しました。'
      render :new
    end
  end

  def show
    @video = Video.find(params[:room_id])
  end

  def update
    @room = Room.find(params[:room_id])
    @video = Video.find(params[:id])
    if @video.update_attributes(video_params)
      redirect_to controller: 'rooms', action: 'show', id: @room.id
      flash[:success] = '動画を編集しました。'
    else
      flash.now[:alert] = '動画の編集に失敗しました。'
      render :edit
    end
  end

  def edit
    @room = Room.find(params[:id])
    @video = Video.find(params[:room_id])
  end

  def destroy
    video = Video.find(params[:room_id])
    video.destroy
    redirect_to room_path
  end

  private
  def video_params
    params.require(:video).permit(:video_name, :youtube_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/homes/index.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            %h1.m-0.text-dark WelcomePage
        .content
          .row.mb-2
            .col-sm-6
              %p= link_to '部屋一覧', rooms_path

app/views/homes/testindex.html.haml
/%h1 Homes#Index
/%p= link_to 'Rooms_Indexへ移動する', rooms_path
/\# 画像対応版
.wrapper
  / Navbar
  %nav.main-header.navbar.navbar-expand.bg-white.navbar-light.border-bottom
    / Left navbar links
    %ul.navbar-nav
      %li.nav-item
        %a.nav-link{"data-widget" => "pushmenu", :href => "#"}
          %i.fa.fa-bars
      %li.nav-item.d-none.d-sm-inline-block
        %a.nav-link{:href => "index3.html"} Home
      %li.nav-item.d-none.d-sm-inline-block
        %a.nav-link{:href => "#"} Contact
    / SEARCH FORM
    %form.form-inline.ml-3
      .input-group.input-group-sm
        %input.form-control.form-control-navbar{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        .input-group-append
          %button.btn.btn-navbar{:type => "submit"}
            %i.fa.fa-search
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
    / Brand Logo
    %a.brand-link{:href => "index3.html"}
      = image_tag "AdminLTELogo.png", alt: "AdminLTE Logo", class: "brand-image img-circle elevation-3", style: "opacity: .8"
      %span.brand-text.font-weight-light AdminLTE 3
    / Sidebar
    .sidebar
      / Sidebar user panel (optional)
      .user-panel.mt-3.pb-3.mb-3.d-flex
        .image
          = image_tag "user2-160x160.jpg", alt: "User Image", class: "img-circle elevation-2"
        .info
          %a.d-block{:href => "#"} Alexander Pierce
      / Sidebar Menu
      %nav.mt-2
        %ul.nav.nav-pills.nav-sidebar.flex-column{"data-accordion" => "false", "data-widget" => "treeview", :role => "menu"}
          /
            Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library
          %li.nav-item.has-treeview.menu-open
            %a.nav-link.active{:href => "#"}
              %i.nav-icon.fa.fa-dashboard
              %p
                Starter Pages
                %i.right.fa.fa-angle-left
            %ul.nav.nav-treeview
              %li.nav-item
                %a.nav-link.active{:href => "#"}
                  %i.fa.fa-circle-o.nav-icon
                  %p Active Page
              %li.nav-item
                %a.nav-link{:href => "#"}
                  %i.fa.fa-circle-o.nav-icon
                  %p Inactive Page
          %li.nav-item
            %a.nav-link{:href => "#"}
              %i.nav-icon.fa.fa-th
              %p
                Simple Link
                %span.right.badge.badge-danger New
      / /.sidebar-menu
    / /.sidebar
  / Content Wrapper. Contains page content
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            %h1.m-0.text-dark Starter Page
          / /.col
          .col-sm-6
            %ol.breadcrumb.float-sm-right
              %li.breadcrumb-item
                %a{:href => "#"} Home
              %li.breadcrumb-item.active Starter Page
          / /.col
        / /.row
      / /.container-fluid
    / /.content-header
    / Main content
    .content
      .container-fluid
        .row
          .col-lg-6
            .card
              .card-body
                %h5.card-title Card title
                %p.card-text
                  Some quick example text to build on the card title and make up the bulk of the card's
                  content.
                %a.card-link{:href => "#"} Card link
                %a.card-link{:href => "#"} Another link
            .card.card-primary.card-outline
              .card-body
                %h5.card-title Card title
                %p.card-text
                  Some quick example text to build on the card title and make up the bulk of the card's
                  content.
                %a.card-link{:href => "#"} Card link
                %a.card-link{:href => "#"} Another link
            .card
              .card-body
                %h5.card-title Card title
                %p.card-text
                  Some quick example text to build on the card title and make up the bulk of the card's
                  content.
                %a.card-link{:href => "#"} Card link
                %a.card-link{:href => "#"} Another link
            .card.card-primary.card-outline
              .card-body
                %h5.card-title Card title
                %p.card-text
                  Some quick example text to build on the card title and make up the bulk of the card's
                  content.
                %a.card-link{:href => "#"} Card link
                %a.card-link{:href => "#"} Another link
            / /.card
          / /.col-md-6

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VideoRooms
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/flash_messages'
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/rooms/edit.html.haml
%h1 Rooms#Edit
= render partial: 'shared/form_room'

app/views/rooms/index.html.haml
= render 'shared/room_all'

app/views/rooms/new.html.haml
= render partial: 'shared/form_room'

app/views/rooms/show.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
        %h1.m-0.text-dark #{@room.room_name}
        = render partial: 'shared/form_video'
        = render partial: 'shared/video_all', collection: @room.videos, as: 'video'

app/views/shared/_flash_messages.html.haml
- flash.each do |msg_type, msg|
  #alert{:class => "alert alert-#{msg_type}", :role => "alert"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    = msg

app/views/shared/_footer.html.haml
%aside.control-sidebar.control-sidebar-dark
  / Control sidebar content goes here
  .p-3
    %h5 Title
    %p Sidebar content
  //.control-sidebar
  / Main Footer
%footer.main-footer
  / To the right
  .float-right.d-none.d-sm-inline
    Anything you want
  / Default to the left
  %strong
    Copyright © 2014-2018
    = succeed "." do
      %a{:href => "https://adminlte.io"} AdminLTE.io
  All rights reserved.

app/views/shared/_form_room.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    .container-fluid
      .row.mb-2
      %hr
        .col-sm-6
          %h1.m-0.text-dark 新しい部屋の作成
          = form_with model: @room, local: true do|f|
            %label RoomName
            .form-group
              = f.text_field :room_name, |
                class: 'form-control', |
                required: true |
            .form-group
              = f.submit value: '送信', class: 'btn btn-primary btn-block'
          %p= link_to '部屋の一覧画面へ戻る', rooms_path

app/views/shared/_form_video.html.haml
.container-fluid
  .row.mb-2
  %hr
    .col-sm-6
      = form_with model: [@room, @video], local: true do |f|
        %label 投稿する動画の名前
        .form-group
          = f.text_field :video_name, |
          class: 'form-control', |
          required: true  |
        %label 動画のURLを入力
        .form-group
          = f.text_field :youtube_url, |
            class: 'form-control', |
            required: true  |
        .form-group
          = f.submit value: '送信', class: 'btn btn-primary'
        %p= link_to '部屋の一覧画面へ戻る', rooms_path

  %hr

app/views/shared/_header.html.haml
.wrapper
  %nav.main-header.navbar.navbar-expand-sm.bg-white.navbar-light.border-bottom
    %ul.navbar-nav
      %li.nav-item
        - if user_signed_in?
          %li.nav-item.d-none.d-sm-inline-block
            = link_to 'PublicRooms', rooms_path, class: 'nav-link'
          %li.nav-item.d-none.d-sm-inline-block
            = link_to 'Users', users_path, class: 'nav-link'
          %li.nav-item.d-none.d-sm-inline-block
            = link_to 'MyRooms', user_path(current_user.id), class: 'nav-link'
          %li.nav-item.d-none.d-sm-inline-block
            = link_to 'Account', edit_user_registration_path, class: 'nav-link'
          %li.nav-item.d-none.d-sm-inline-block
            = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item.d-none.d-sm-inline-block
            = link_to "Sign up", new_user_registration_path, class: 'btn nav-link'
          %li.nav-item.d-none.d-sm-inline-block
            = link_to "Log in", new_user_session_path, class: 'nav-link'
  / Main Sidebar Container
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
    / Brand Logo
    %a.brand-link{:href => "/"}
      = image_tag "AdminLTELogo.png", alt: "AdminLTE Logo", class: "brand-image img-circle elevation-3", style: "opacity: .8"
      %span.brand-text.font-weight-light VideoRooms

app/views/shared/_room_all.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            %h1.m-0.text-dark シェアルーム
            %button.btn.btn-default.m-1=link_to '新しい部屋を作る', new_room_path
      .content
        .row
          - @rooms.each do |room|
            .col-lg-6.d-flex
              .card.card-primary.card-outline
                .card-body
                  %h1.card-title #{room.room_name}
                  %p.card-text
                    ココに入る内容は部屋を作成する際の情報を記載するところです。
                    この部屋を何用にするか考えてみましょう。
                  %button.btn.btn-default= link_to '部屋に入る', room_path(room.id)
                  %button.btn.btn-outline-warning= link_to '部屋を削除する', room_path(room), method: :delete, data: { confirm: '削除しますか？' }

        /%span 部屋ID:
        /= room.id
        /%span 部屋名:
        /= link_to room.room_name, room_path(room.id)
        /%span email:
        /= link_to room.user.email, user_path(room.user.id)
        /%td
        /   link_to '編=集', edit_room_path(room)
        /  = link_to '削除', room_path(room), method: :delete, data: { confirm: '削除しますか？' }

app/views/shared/_video_all.html.haml
.wrapper
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h5
          %span 動画名 :
          = video.video_name
          %button.btn-sm.btn-outline-warning= link_to '削除', room_video_path(video), method: :delete, data: { confirm: '削除しますか？' }
          %iframe{ allow: 'accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture',
            allowfullscreen: '',
            frameborder: '0',
            height: '315',
            src: "https://www.youtube.com/embed/#{ video.youtube_url }",
            width: '560' }
      /= link_to '編集', edit_room_video_path(video)

app/views/shared/_video_index.html.haml
%p
  %span 動画ID :
  = video.id
  %span 動画名 :
  = link_to video.video_name, room_video_path(video.id)
  = link_to '削除', room_video_path(video), method: :delete, data: { confirm: '削除しますか？' }

app/views/shared/_video_new.html.haml
= form_with model: [@room, @video], local: true do |f|
  %p 動画の名前
  = f.text_field :video_name
  = f.submit value: '送信'
%p= link_to '部屋一覧', rooms_path

app/views/users/index.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-0
          %h1.m-0.text-dark ユーザー一覧
          .table-container
          %table.table.table-striped
            %thead.bg-gradient-primary.text-white
              %tr
                %th.w-1 No.
                %th.w-3 Address
                %th.w-5 MyRooms
            %tbody
              - @users.each.with_index(1) do |user, i|
                %tr
                  %td= i
                  %td= user.email
                  %td= link_to "info", user_path(user.id)

app/views/users/show.html.haml
.wrapper
  %aside.main-sidebar.sidebar-dark-primary.elevation-4
  .content-wrapper
    / Content Header (Page header)
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-0
          %h1.m-0.text-dark 作成した部屋
          .table-container
          %table.table.table-striped
            %thead.bg-gradient-primary.text-white
              %tr
                %th.w-1 No.
                %th.w-3 RoomName
                %th.w-5 RoomLink
            %tbody
              - @rooms.each.with_index(1) do |room, i|
                %tr
                  %td= i
                  %td= room.room_name
                  %td= link_to "Go!", room_path(room.id)

app/views/videos/edit.html.haml
%h1 Videos#Edit
= render partial: 'shared/form_video'

app/views/videos/new.html.haml
%h1 Videos#New
= render partial: 'shared/form_video'

app/views/videos/show.html.haml
%h1
  Videos#Show : #{@video.video_name}